<?php

namespace AppBundle\Repository;

/**
 * UsersOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
